### PR TITLE
Added a tutorial

### PR DESCRIPTION
**Pull request by Abdul-Hafeez-Galib**
Added a Introduction to Algorithms course by MIT OpenCourseWare.

### CODE REVIEW

**Review by Vishruth-S — APPROVED** [review]

**Comment by Vishruth-S** [comment]
Sorry, this PR had merge conflicts, please send another one.

**Comment by Abdul-Hafeez-Galib** [comment]
Hi! 
Could you please tell what was the conflict?

**Comment by Abdul-Hafeez-Galib** [comment]
Sorry for the inconvenience.
I added this already.

**Comment by Abdul-Hafeez-Galib** [comment]
By mistake I sent it twice as this one had indentation problem.

**Pull request closed without merging**
