### PR TITLE
Added a very good cp guide alongwith practice problems.

### PR DESCRIPTION
**Pull request by nihal-ahmad**
Hey there!, Thanks for submitting a PR to this repo
Please complete the following checklist for your PR to be approved. Mark the items by adding an `x`.   
Example:  - [ ] Mark me as completed  
To mark: - [x] Mark me as completed

- [ x] My Pull Request adheres to the **Contribution guidelines**.
- [ x] I have added `readme.md` and `solution` files in the **appropriate folder**.
- [ x] The solution I have given is my **own** and not plagiarized in any form.
- [ x] My solution passes all the testcases.
- [ x] I have properly indented and **documented my solution using comments**.

If any of the above is unmarked, please make the necessary changes and then mark them so that you're PR can be approved and merged.

### CODE REVIEW

**Comment by nihal-ahmad** [comment]
Already added comments in form of time and space complexity, what else
should I add, can you elaborate please?

**Comment by nihal-ahmad** [comment]
@Vishruth-S made necessary comments , please review my pr now

**Comment by nihal-ahmad** [comment]
@Vishruth-S i have added approach to the solution at the beginning of the solution in comments form . but then also your bot not accepting my pr. please manually review it .

**Review by Vishruth-S — APPROVED** [review]

**Comment by nihal-ahmad** [comment]
@Vishruth-S is my pr still open, do i have to do something more? please help me understand your guidelines of contributing.

**Pull request merged**
