### PR TITLE
Added GFG Problem

### PR DESCRIPTION
**Pull request by logan0501**
Hey there!, Thanks for submitting a PR to this repo
Please complete the following checklist for your PR to be approved. Mark the items by adding an `x`.   
Example:  - [ ] Mark me as completed  
To mark: - [x] Mark me as completed

- [x] My Pull Request adheres to the **Contribution guidelines**.
- [x] I have added `readme.md` and `solution` files in the **appropriate folder**
- [x] None of the folder and file names I have added contain any **invalid characters, leading digits or trailing whitespaces**
- [x] The solution I have given is my **own** and not plagiarized in any form.
- [x] My solution passes all the testcases.
- [x] I have properly indented and **documented my solution using comments**.

If any of the above is unmarked, please make the necessary changes and then mark them so that you're PR can be approved and merged.

### CODE REVIEW

**Comment by logan0501** [comment]
I didn't add any leetcode problems in my local repo, but it shows error in leetcode problem. It was in my stagging area too. But i don't know how i got this. Kindly  review this and help me. 
Thank you

**Comment by R-Ayush777** [comment]
@logan0501
I am having same issue, in my PR

**Comment by logan0501** [comment]
@R-Ayush777  How shall we approach them.

**Comment by R-Ayush777** [comment]
Hey @logan0501, How to resolve the issue I don't know how to resolve if u find any solution plz suggest me as well 
Do I have to close the current PR and then issue a new PR?

**Comment by logan0501** [comment]
@R-Ayush777  How to close and issue a new PR

**Comment by R-Ayush777** [comment]
In the blow area of your pull request, I believe you can see a close PR option. As a result, close it and create a new PR with
Delete the repo that was previously forked. and fork new one(this repo.) so that whatever problem there is is resolved. and create new PR.

**Comment by logan0501** [comment]
Ok thanks

**Pull request closed without merging**
